//! Pure core: types and decisions, no I/O.
pub mod agent_event;
pub mod diagnosis;
pub mod disk;
pub mod guest_reply;
pub mod hostname;
pub mod ids;
pub mod memory;
pub mod metrics;
pub mod outcome;
pub mod s3;
pub mod save;
pub mod settings;
pub mod settings_recovery;
pub mod snapshot;
pub mod spec;
pub mod task;
pub mod telemetry;
pub mod usage;
